angular.module('nicoco').value('horses', [
	{src: 'images/horses/101.jpg', desc: ''},
	{src: 'images/horses/102.jpg', desc: ''},
	{src: 'images/horses/103.jpg', desc: ''},
	{src: 'images/horses/104.jpg', desc: ''},
	{src: 'images/horses/105.jpg', desc: ''},
	{src: 'images/horses/1018.jpg', desc: 'alexandra evang workshop 2017 (Renesse) - www.alexandraevang.de'},
	{src: 'images/horses/106.jpg', desc: ''},
	{src: 'images/horses/107.jpg', desc: ''},
	{src: 'images/horses/108.jpg', desc: ''},
	{src: 'images/horses/109.jpg', desc: ''},
	{src: 'images/horses/1010.jpg', desc: ''},
	{src: 'images/horses/1011.jpg', desc: ''},
	{src: 'images/horses/1012.jpg', desc: ''},
	{src: 'images/horses/1013.jpg', desc: ''},
	{src: 'images/horses/1014.jpg', desc: ''},
	{src: 'images/horses/1015.jpg', desc: ''},
]);
