angular.module('nicoco').value('horses', [
	{src: 'images/horses/1.jpg', desc: ''},
	{src: 'images/horses/2.jpg', desc: ''},
	{src: 'images/horses/3.jpg', desc: ''},
	{src: 'images/horses/4.jpg', desc: ''},
	{src: 'images/horses/5.jpg', desc: ''},
	{src: 'images/horses/18.jpg', desc: 'alexandra evang workshop 2017 (Renesse) - www.alexandraevang.de'},
	{src: 'images/horses/6.jpg', desc: ''},
	{src: 'images/horses/7.jpg', desc: ''},
	{src: 'images/horses/8.jpg', desc: ''},
	{src: 'images/horses/9.jpg', desc: ''},
	{src: 'images/horses/10.jpg', desc: ''},
	{src: 'images/horses/11.jpg', desc: ''},
	{src: 'images/horses/12.jpg', desc: ''},
	{src: 'images/horses/13.jpg', desc: ''},
	{src: 'images/horses/14.jpg', desc: ''},
	{src: 'images/horses/15.jpg', desc: ''},
]);
