angular.module('nicoco').value('weddings', [
	{src: 'images/wedding/1.png', desc: ''},
	{src: 'images/wedding/2.png', desc: ''},
	{src: 'images/wedding/3.png', desc: ''},
	{src: 'images/wedding/4.png', desc: ''},
	{src: 'images/wedding/5.png', desc: ''},
	{src: 'images/wedding/6.png', desc: ''},
	{src: 'images/wedding/7.png', desc: ''},
	{src: 'images/wedding/8.png', desc: ''},
	{src: 'images/wedding/9.png', desc: ''},
	{src: 'images/wedding/10.png', desc: ''},
	{src: 'images/wedding/11.png', desc: ''},
	{src: 'images/wedding/12.png', desc: ''},
	{src: 'images/wedding/13.png', desc: ''},
	{src: 'images/wedding/14.png', desc: ''},
	{src: 'images/wedding/15.png', desc: ''},
	{src: 'images/wedding/16.png', desc: ''},
	{src: 'images/wedding/17.png', desc: ''},
	{src: 'images/wedding/18.png', desc: ''},
	{src: 'images/wedding/19.png', desc: ''},
	{src: 'images/wedding/20.png', desc: ''},
	{src: 'images/wedding/21.png', desc: ''},
	{src: 'images/wedding/22.png', desc: ''},
	{src: 'images/wedding/23.png', desc: ''}
]);
